export CLUSTER="scholar"
export PROCS="40"
export CLUMP="true"
export WALLTIME="72:00:00"
export frh="0"
export rrh="0"
export NODES="2"
export PPN="20"
qsub -q "$CLUSTER" -l nodes=$NODES:ppn=$PPN,walltime=$WALLTIME "clumped_run.sh"