export SIMPATH="/scratch/scholar/rkumaran/Simulation_space"
export STARLOC="/home/rkumaran/Desktop/star/13.04.010-R8/STAR-CCM+13.04.010-R8/star/bin/starccm+"
export PODKEY="iOJDZCUKWsPIjut3CFrKXQ"
export PROCESSES="20"
export CP="/home/rkumaran/fsaeSTAR/src"



export FILENAME="BASESIM_25-1_WT.sim"
export newName="WT_BASELINE_13.sim"
export MACRO="macroController.java"
export frh="0"
export rrh="0"
export rws="0"
export fws="0"
export uts="0"
export cs="0"
export ps="0"
export sceneMultiplier="0"
export yaw="0"
export roll="0"
export domainSet="full"
export freestream="13.76"
export maxSteps="1000"
export preprocess="true"
export process="false"
export postprocess="false"
export windTunnel="true"

"$STARLOC" "$SIMPATH/$FILENAME" -batch "$CP/$MACRO" -machinefile $PBS_NODEFILE -cpubind -rsh ssh -np $PROCESSES -podkey $PODKEY -classpath "$CP" -power


export FILENAME="BASESIM_25-1_WT.sim"
export newName="WT_BASELINE_18.sim"
export MACRO="macroController.java"
export frh="0"
export rrh="0"
export rws="0"
export fws="0"
export uts="0"
export cs="0"
export ps="0"
export sceneMultiplier="0"
export yaw="0"
export roll="0"
export domainSet="full"
export freestream="18.38"
export maxSteps="1000"
export preprocess="true"
export process="false"
export postprocess="false"
export windTunnel="true"

"$STARLOC" "$SIMPATH/$FILENAME" -batch "$CP/$MACRO" -machinefile $PBS_NODEFILE -cpubind -rsh ssh -np $PROCESSES -podkey $PODKEY -classpath "$CP" -power


export FILENAME="BASESIM_25-1_WT.sim"
export newName="WT_BASELINE_27.sim"
export MACRO="macroController.java"
export frh="0"
export rrh="0"
export rws="0"
export fws="0"
export uts="0"
export cs="0"
export ps="0"
export sceneMultiplier="0"
export yaw="0"
export roll="0"
export domainSet="full"
export freestream="27.54"
export maxSteps="1000"
export preprocess="true"
export process="false"
export postprocess="false"
export windTunnel="true"

"$STARLOC" "$SIMPATH/$FILENAME" -batch "$CP/$MACRO" -machinefile $PBS_NODEFILE -cpubind -rsh ssh -np $PROCESSES -podkey $PODKEY -classpath "$CP" -power


export FILENAME="BASESIM_25-1_WT.sim"
export newName="WT_YAW_3_18.sim"
export MACRO="macroController.java"
export frh="0"
export rrh="0"
export rws="0"
export fws="0"
export uts="0"
export cs="0"
export ps="0"
export sceneMultiplier="0"
export yaw="3"
export roll="0"
export domainSet="full"
export freestream="27.54"
export maxSteps="1000"
export preprocess="true"
export process="false"
export postprocess="false"
export windTunnel="true"

"$STARLOC" "$SIMPATH/$FILENAME" -batch "$CP/$MACRO" -machinefile $PBS_NODEFILE -cpubind -rsh ssh -np $PROCESSES -podkey $PODKEY -classpath "$CP" -power


export FILENAME="BASESIM_25-1_WT.sim"
export newName="WT_YAW_3_27.sim"
export MACRO="macroController.java"
export frh="0"
export rrh="0"
export rws="0"
export fws="0"
export uts="0"
export cs="0"
export ps="0"
export sceneMultiplier="0"
export yaw="3"
export roll="0"
export domainSet="full"
export freestream="27.54"
export maxSteps="1000"
export preprocess="true"
export process="false"
export postprocess="false"
export windTunnel="true"

"$STARLOC" "$SIMPATH/$FILENAME" -batch "$CP/$MACRO" -machinefile $PBS_NODEFILE -cpubind -rsh ssh -np $PROCESSES -podkey $PODKEY -classpath "$CP" -power


export FILENAME="BASESIM_25-1_WT.sim"
export newName="WT_YAW_6_18.sim"
export MACRO="macroController.java"
export frh="0"
export rrh="0"
export rws="0"
export fws="0"
export uts="0"
export cs="0"
export ps="0"
export sceneMultiplier="0"
export yaw="6"
export roll="0"
export domainSet="full"
export freestream="27.54"
export maxSteps="1000"
export preprocess="true"
export process="false"
export postprocess="false"
export windTunnel="true"

"$STARLOC" "$SIMPATH/$FILENAME" -batch "$CP/$MACRO" -machinefile $PBS_NODEFILE -cpubind -rsh ssh -np $PROCESSES -podkey $PODKEY -classpath "$CP" -power


export FILENAME="BASESIM_25-1_WT.sim"
export newName="WT_YAW_6_27.sim"
export MACRO="macroController.java"
export frh="0"
export rrh="0"
export rws="0"
export fws="0"
export uts="0"
export cs="0"
export ps="0"
export sceneMultiplier="0"
export yaw="6"
export roll="0"
export domainSet="full"
export freestream="27.54"
export maxSteps="1000"
export preprocess="true"
export process="false"
export postprocess="false"
export windTunnel="true"

"$STARLOC" "$SIMPATH/$FILENAME" -batch "$CP/$MACRO" -machinefile $PBS_NODEFILE -cpubind -rsh ssh -np $PROCESSES -podkey $PODKEY -classpath "$CP" -power


export FILENAME="BASESIM_25-1_WT.sim"
export newName="WT_YAW_9_18.sim"
export MACRO="macroController.java"
export frh="0"
export rrh="0"
export rws="0"
export fws="0"
export uts="0"
export cs="0"
export ps="0"
export sceneMultiplier="0"
export yaw="9"
export roll="0"
export domainSet="full"
export freestream="27.54"
export maxSteps="1000"
export preprocess="true"
export process="false"
export postprocess="false"
export windTunnel="true"

"$STARLOC" "$SIMPATH/$FILENAME" -batch "$CP/$MACRO" -machinefile $PBS_NODEFILE -cpubind -rsh ssh -np $PROCESSES -podkey $PODKEY -classpath "$CP" -power


export FILENAME="BASESIM_25-1_WT.sim"
export newName="WT_YAW_9_27.sim"
export MACRO="macroController.java"
export frh="0"
export rrh="0"
export rws="0"
export fws="0"
export uts="0"
export cs="0"
export ps="0"
export sceneMultiplier="0"
export yaw="9"
export roll="0"
export domainSet="full"
export freestream="27.54"
export maxSteps="1000"
export preprocess="true"
export process="false"
export postprocess="false"
export windTunnel="true"

"$STARLOC" "$SIMPATH/$FILENAME" -batch "$CP/$MACRO" -machinefile $PBS_NODEFILE -cpubind -rsh ssh -np $PROCESSES -podkey $PODKEY -classpath "$CP" -power


export FILENAME="BASESIM_25-1_WT.sim"
export newName="WT_YAW_12_18.sim"
export MACRO="macroController.java"
export frh="0"
export rrh="0"
export rws="0"
export fws="0"
export uts="0"
export cs="0"
export ps="0"
export sceneMultiplier="0"
export yaw="12"
export roll="0"
export domainSet="full"
export freestream="27.54"
export maxSteps="1000"
export preprocess="true"
export process="false"
export postprocess="false"
export windTunnel="true"

"$STARLOC" "$SIMPATH/$FILENAME" -batch "$CP/$MACRO" -machinefile $PBS_NODEFILE -cpubind -rsh ssh -np $PROCESSES -podkey $PODKEY -classpath "$CP" -power


export FILENAME="BASESIM_25-1_WT.sim"
export newName="WT_YAW_12_27.sim"
export MACRO="macroController.java"
export frh="0"
export rrh="0"
export rws="0"
export fws="0"
export uts="0"
export cs="0"
export ps="0"
export sceneMultiplier="0"
export yaw="12"
export roll="0"
export domainSet="full"
export freestream="27.54"
export maxSteps="1000"
export preprocess="true"
export process="false"
export postprocess="false"
export windTunnel="true"

"$STARLOC" "$SIMPATH/$FILENAME" -batch "$CP/$MACRO" -machinefile $PBS_NODEFILE -cpubind -rsh ssh -np $PROCESSES -podkey $PODKEY -classpath "$CP" -power


export FILENAME="BASESIM_25-1_WT.sim"
export newName="WT_YAW_15_18.sim"
export MACRO="macroController.java"
export frh="0"
export rrh="0"
export rws="0"
export fws="0"
export uts="0"
export cs="0"
export ps="0"
export sceneMultiplier="0"
export yaw="15"
export roll="0"
export domainSet="full"
export freestream="27.54"
export maxSteps="1000"
export preprocess="true"
export process="false"
export postprocess="false"
export windTunnel="true"

"$STARLOC" "$SIMPATH/$FILENAME" -batch "$CP/$MACRO" -machinefile $PBS_NODEFILE -cpubind -rsh ssh -np $PROCESSES -podkey $PODKEY -classpath "$CP" -power


export FILENAME="BASESIM_25-1_WT.sim"
export newName="WT_YAW_15_27.sim"
export MACRO="macroController.java"
export frh="0"
export rrh="0"
export rws="0"
export fws="0"
export uts="0"
export cs="0"
export ps="0"
export sceneMultiplier="0"
export yaw="15"
export roll="0"
export domainSet="full"
export freestream="27.54"
export maxSteps="1000"
export preprocess="true"
export process="false"
export postprocess="false"
export windTunnel="true"

"$STARLOC" "$SIMPATH/$FILENAME" -batch "$CP/$MACRO" -machinefile $PBS_NODEFILE -cpubind -rsh ssh -np $PROCESSES -podkey $PODKEY -classpath "$CP" -power


